/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "X.h"
#include "Y.h"
#include "Pin_x_aliases.h"
#include "Pin_x.h"
#include "Pin_y_aliases.h"
#include "Pin_y.h"
#include "isr_clk.h"
#include "Pin_in_clk_aliases.h"
#include "Pin_in_clk.h"
#include "CLOCK.h"
#include "Clock_1.h"
#include "Pin_out_clk1_aliases.h"
#include "Pin_out_clk1.h"
#include "Pin_out_clk2_aliases.h"
#include "Pin_out_clk2.h"
#include "UART.h"
#include "isr_bluetooth.h"
#include "data_out_aliases.h"
#include "data_out.h"
#include "signX_aliases.h"
#include "signX.h"
#include "signY_aliases.h"
#include "signY.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

